vmware/vsphere-automation-sdk-python

- README.md
Remove whitespace, I think that this is typo error
> Fix typo error, remove whitespace.

- samples/vsphere/vcenter/vm/delete_vm.py
Signed-off-by: Pavan Bidkar <pbidkar@vmware.com>
> Adding New Sample to Delete User specified Virtual Machine

- samples/vmc/sddc/add_remove_hosts.py
- samples/vmc/sddc/create_delete_sddc.py
> Add exception handling for sddc samples to get detailed error message

- samples/vmc/sddc/connect_to_vsphere_with_default_sddc_password.py
Sample output:
VM ID    VM Name
-------  ----------------------------------------------------------
vm-35    vcenter
vm-50    nsx-manager
vm-51    Node-7c1f558c-d026-4e48-be2b-f0bb6e6c220f-NSX-controller-1
vm-52    Node-db8fda3f-f611-4631-a3ac-700ab6412ea0-NSX-controller-2
vm-53    Node-844750bc-0191-45da-9a0d-1f849de2ea08-NSX-controller-3
> Add connect to vmc vsphere sample

- samples/vmc/networks/expose_public_ip.py
> add expose vm to public internet sample

- samples/vmc/sddc/README.md
> Add README to describe VMC sddc samples and their prerequisites.

- samples/vmc/README.md
> Updated VMC Readme

- README.md
- samples/vmc/sddc/sddc_crud.py
> add account linking config when creating sddc

- .travis.yml
- samples/vsphere/backuprestore/backup_schedule.py
- samples/vsphere/common/sso.py
- samples/vsphere/common/vim/file.py
- samples/vsphere/logforwarding/log_forwarding.py
- samples/vsphere/services/services_list.py
- samples/vsphere/vcenter/vm/hardware/adapter/scsi.py
- samples/vsphere/vcenter/vm/hardware/boot_device.py
- samples/vsphere/vcenter/vm/hardware/cdrom.py
- samples/vsphere/vcenter/vm/hardware/cpu.py
- samples/vsphere/vcenter/vm/hardware/ethernet.py
- samples/vsphere/vcenter/vm/hardware/floppy.py
- samples/vsphere/vcenter/vm/hardware/memory.py
- setup.cfg
- test-requirements.txt
- tests/test_vsphere_client.py
Add unittests for vsphere client
Fixed some format issues
Run the tests as part of travis ci
> Add tests to make sure vsphere client stubs are present

- samples/vsphere/contentlibrary/README.md
- samples/vsphere/contentlibrary/lib/cls_api_helper.py
- samples/vsphere/contentlibrary/ovaimport/signed_ova_import.py
Signed-off-by: het <het@vmware.com>
> signed ova import sample

- samples/vsphere/common/vim/helpers/vim_utils.py
- samples/vsphere/tagging/tagging_workflow.py
Add API call to retrieve category and tag name and description.
Signed-off-by: het <het@vmware.com>
> Rewrite tagging sample to use vsphere client

- requirements.txt
- samples/vmc/helpers/vmc_task_helper.py
- samples/vmc/networks/dns_crud.py
- samples/vmc/networks/firewall_rules_crud.py
- samples/vmc/networks/ipsec_vpns_crud.py
- samples/vmc/networks/logical_network_crud.py
- samples/vmc/networks/nat_rule_crud.py
- samples/vmc/networks/public_ip_crud.py
- samples/vmc/orgs/organization_operations.py
- samples/vmc/sddc/connect_to_vsphere_with_default_sddc_password.py
- samples/vmc/sddc/sddc_crud.py
- samples/vsphere/backuprestore/backup_job_list.py
- samples/vsphere/backuprestore/backup_schedule.py
- samples/vsphere/logforwarding/log_forwarding.py
- samples/vsphere/services/services_list.py
Signed-off-by: het <het@vmware.com>
> Remove tabulate from the dependency list

- samples/vmc/networks_nsxt/cgw_firewall_crud.py
- samples/vmc/networks_nsxt/nat_crud.py
CRUD Public IP
CRUD NAT Rule
CRUD Group
CRUD CGW Firewall
Signed-Off-By: Tripti Attavar <tattavar@vmware.com>
> Add NSXT sample for NAT and CGW firewall

- samples/vmc/networks_nsxt/dfw_firewall_crud.py
CRUD Group
CRUD Communication Map
CRUD DFW Firewall
Signed-Off-By: Tripti Attavar tattavar@vmware.com
> Add NSXT sample for DFW firewall

- README.md
- removed previous instructions to install the SDK
- added new commands needed for installation
> updating new installation instructions

- setup.py
Signed-off-by: Kunal Singh<singhk@vmware.com>
> Updated the setup.py version for M8 relase

- samples/vmc/sddc/sddc_crud.py
Signed-off-by: Jobin George<jgeorge@vmware.com>
> Modified sddc_crud sample to fix multiple issues.

- samples/vsphere/vcenter/certificatemanagement/README.md
- samples/vsphere/vcenter/certificatemanagement/gencsr.py
- samples/vsphere/vcenter/certificatemanagement/get_tls_certificate.py
- samples/vsphere/vcenter/certificatemanagement/renew_tls_certificate.py
- samples/vsphere/vcenter/certificatemanagement/replace_tls_certificate.py
- samples/vsphere/vcenter/certificatemanagement/replace_tls_certificate_with_vmca_signed.py
- samples/vsphere/vcenter/certificatemanagement/replace_vmca_root.py
- samples/vsphere/vcenter/certificatemanagement/trusted_root_chains_create.py
- samples/vsphere/vcenter/certificatemanagement/trusted_root_chains_delete.py
- samples/vsphere/vcenter/certificatemanagement/trusted_root_chains_get.py
- samples/vsphere/vcenter/certificatemanagement/trusted_root_chains_list.py
- samples/vsphere/vcenter/namespace_management/supervisor_services/list_supervisor_services.py
- samples/vsphere/vcenter/namespace_management/supervisor_services/list_supervisor_services_on_cluster.py
Signed-off-by: shweta purohit <spurohit@vmware.com>
> new samples for 7032 release

- README.md
Signed-off-by: Shweta Purohit <spurohit@vmware.com>
> Update README with correct gitub url

- README.md
Updated ReadMe on Releases for VMC and NSX
> Updated ReadMe on Releases for VMC and NSX

- README.md
For preview of changes please refer to https://github.com/aagrawal3/vsphere-automation-sdk-python landing page.
> Update Python API documentation text in README.

- README.md
Updating the GitHub portal's support section
Signed-off-by: Prajwal Bhagat <bhagatp@vmware.com>
> Updating the GitHub portal's support section

- README.md
Rendering can be reviewed at https://github.com/aagrawal3/vsphere-automation-sdk-python/tree/master?tab=readme-ov-file#support
> Update support details.
