README.md
Signed-off-by: Travis Finch <travisfinch@gmail.com>
=> Add DCO information

samples/vsphere/vcenter/vm/hardware/serial.py
When re-run the sample without cleanup previous port the power
on peration may time out due to the output file exist already.
Remove the file before creating new port and add notes to
help avoiding this.
=> Remove the output file before creating new serial port

samples/vsphere/vcenter/vm/hardware/parallel.py, samples/vsphere/vcenter/vm/hardware/serial.py
Need to make the same fix as the one in #13 for parallel port.
Also move the cleanup_backends to the main sample run to make
sure the output file is always deleted.
=> Remove the output file before creating the parallel port

samples/vsphere/vcenter/vm/create/create_basic_vm.py, samples/vsphere/vcenter/vm/create/create_default_vm.py, samples/vsphere/vcenter/vm/create/create_exhaustive_vm.py, samples/vsphere/vcenter/vm/hardware/disk.py
Update the configuration inputs to reference the “VM” designated values in the testbed.py file
Also removed the unused prerequisites from the comments.
Verified to work against vSphere 6.5 GA and Python 3.6.
Signed-off-by: Kyle Ruddy <kmruddy@gmail.com>
=> Update configuration inputs

samples/vsphere/common/sample_template.py
=> Add sample template file

samples/vsphere/common/sample_template.py
Use service manager to connect to both vAPI and VIM services
=> Update sample template

README.md, sample_template/README.md, sample_template/sample_template.py
Move sample template out of sample folder. And mention the file in README - Submitting samples section.
=> update sample template and doc

sample_template/sample_template.py, samples/vsphere/common/sample_cli.py, samples/vsphere/common/sample_util.py, samples/vsphere/contentlibrary/ovfdeploy/deploy_ovf_template.py, samples/vsphere/sso/embedded_psc_sso_workflow.py, samples/vsphere/vcenter/setup/main.py, samples/vsphere/vcenter/setup/testbed.py, samples/vsphere/vcenter/vm/create/create_basic_vm.py, samples/vsphere/vcenter/vm/create/create_default_vm.py, samples/vsphere/vcenter/vm/create/create_exhaustive_vm.py, samples/vsphere/vcenter/vm/delete_vm.py, samples/vsphere/vcenter/vm/list_vms.py, samples/vsphere/vcenter/vm/main.py
1. Make sample code more consistent
2. Improve input parameter parser
=> Improve sample code

samples/vsphere/common/sso.py
Make the sso.py python3 compatible.
Add acquire token by token support.
Add hok token support.
=> Add hok token support for sso.py

samples/vmc/sddc/deploy_ovf_template.py
python /Users/het/github/vsphere-automation-sdk-python/samples/vmc/sddc/deploy_ovf_template_cloud.py -s 'vc_fqdn' -u 'cloudadmin@vmc.local' -p 'xxx' -c --libitemname 'ovf_template_1'
vcenter server = vcenter.xxxx.vmc.vmware.com
vc username = cloudadmin@vmc.local
Resource pool ID: resgroup-49
Library item ID: fee53f7d-4c36-4bea-931c-4c4405d5f496
Found an OVF template: ovf_template_1 to deploy.
Deployment successful. Result resource: VirtualMachine, ID: vm-95
VM (vm-95) is deleted
=> add deploy ovf template in cloud sddc sample

samples/vsphere/backuprestore/backup_job_list.py
dict.itervalues is deprecated in Python3. Fixing samples to call method dict.values() works for Python 2.7 & 3
Tested change in Python3 & Python 2.7
Start time           Duration  Type    Status     Location
=> dict.itervalues is deprecated in Python3. Fixing sample

README.md
I've added an example of the pip install command for OSX which illustrates what's expected as the --extra-index-url.
=> Add example pip install

README.md
Make vmc-app link "NSX VMC Cloud Service" and include some
explanatory text for each link.
Signed-Off-By: Gordon Good <ggood@vmware.com>
=> Update links for NSX-T API docs

samples/vmc/networks_nsxt/hello_world.py
Define a directory for NSX-T sample code. Add a basic
example that shows how to authenticate to VMC/NSX-T and
make a simple read call.
Signed-Off-By: Gordon Good <ggood@vmware.com>
=> Add networks_nsxt dir, simple example

sample_template/README.md, sample_template/sample_template_basic.py, sample_template/sample_template_complex.py
The current sample template treat sample as a class. It work well for complex samples when setup and cleanup are needed and some logic is in place. However it's not needed for basic samples which just demo one or two API usage. The code snippets with self. are also hard to use for users who just want to copy/paste to their script. Creating another template for basic samples.
Other example of such simple samples are: https://github.com/vmware/vsphere-automation-sdk-python/tree/master/samples/vmc/tasks
=> Add a basic sample template for simple samples

samples/vmc/networks_nsxt/segments_firewall_crud.py
- GET Infra, Tier1s
- GET segments
- GET domains
- Firewall CRUD operations
=> Added NSXT sample that demonstrates the following operations:

setup.py
As we don't have all dependencies in PyPI, this enables users to install the package directly from repository using `pip`. References the issues #38 and #161. 
It was tested with both Python2 and Python3 on CentOS and Photon containers, Mac OS X and Windows 10. Test results are posted in discussion of #38.
Requires newer version of `setuptools`.
**After** merging it should be possible to install the package with the following commands.
```
pip install --upgrade pip setuptools
pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git
```
The line `git+https://github.com/vmware/vsphere-automation-sdk-python.git` could also be added to _requirements.txt_ and installed along with other requirements.
**Notes**
* _setup.py_ should be maintained accordingly, in case …
=> pip install from repository

setup.py
This PR optimises pip setup by referencing already cloned files instead of downloading them from https git repo.
It also simplifies version management and installation by removing any repository specific information (branch/tag/commit) from setup.py. Each version of repo (tag/branch/commit) can have its own mapping between setup.py and wheel names.
After merging the same installation method should still be used: 
```
pip install --upgrade pip setuptools
pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git`
```
This method was tested across different OS Versions (Linux CentOS/Photon, Mac OS X, Windows). 
Find below the test results:
Notes: 
* With current implementation of PEP 440 in pip/setuptools we still need to `localhost` in path url to have …
=> Optimized setup.py for version control

samples/vmc/networks_nsxt/l3_vpn_crud.py
Signed-off-by: chandrashekh-vmw <chandrashekh@vmware.com>
Make sure the samples runs in both python2 and python3. - **TESTED**
Wrap long lines. - **DONE**
You can check format by execute: - **DONE**
$ pip install -r test-requirements.txt
$ pycodestyle samples tests
=> Examples for L3VPN CRUD operations

samples/vsphere/appliances/health_messages.py
Adding new sample to appliance .Sample demonstrates getting Health messages for various health items .Retrieves Health messages details from vCenter and prints the data.
=> New sample for appliance Health

samples/vmc/draas/__init__.py, samples/vmc/draas/deploy_additional_instance.py, samples/vmc/draas/helpers/__init__.py, samples/vmc/draas/helpers/draas_task_helper.py, samples/vmc/draas/site_recovery_activation_ops.py, samples/vmc/draas/site_recovery_info.py
Signed-Off-by: Jobin George<jgeorge@vmware.com>
=> DRaaS Samples

samples/vmc/draas/activate_srm_ops.py, samples/vmc/draas/deploy_additional_node.py, samples/vmc/draas/get_srm_info.py, samples/vsphere/appliances/get_service.py, samples/vsphere/appliances/list_service.py
Signed-off-by: Kunal Singh <singhk@vmware.com>
=> Samples for VMC M9 release

samples/vmc/draas/activate_srm_ops.py, samples/vmc/draas/deploy_additional_node.py, samples/vmc/draas/get_srm_info.py
Changing DRaaS samples to use `vmc_client.draas` instead of `create_vmc_draas_client` which is not supported
Signed-off-By: Anusha Hegde<anushah@vmware.com>
=> changing draas client to vmc_client.draas

samples/vsphere/appliances/monitoring_query.py
This sample shows how to use the appliance `Monitoring` interface.
The sample calls:
1. `Monitoring.list()` API to obtain list of counters.
2. `Monitoring.query()` API to obtain CPU and Memory statistics for the
last 5 days
Sample output (table with formatted time series data):
```
vcenter server = sc2-rdops-vm06-dhcp-192-66.eng.vmware.com
vc username = administrator@vsphere.local
Example: Query Monitoring for Timeseries Data:
-------------------
Metric                   2021-01-11              2021-01-12              2021-01-13              
cpu.totalfrequency       4788.91000000003        4788.910000000093       4788.910000000022       
cpu.systemload           0.6416814159292042      0.567210599721061       0.5591065830721007      
mem.util                 12477816.737463126 …
```
=> Sample for using appliance Monitoring

README.md, samples/vsphere/vcenter/vm/guest/guest_ops.py, setup.py
Updated `README`, `setup.py` and adding a new `guest_ops` sample for **vSphere 7.0 U2** release
=> 7.0U2 readiness

samples/vsphere/vcenter/namespace_management/list_clusters.py
Sample output:
```
(venv) spurohit@spurohit-a01 vsphere-automation-sdk-python % python samples/vsphere/vcenter/vm/test.py  -s 10.192.194.251 -u Administrator@vsphere.local -p Admin\!23 -v
vcenter server = 10.192.194.251
vc username = Administrator@vsphere.local
Session ID :  2bba9a789989d20ed9cfafa30a16b9d7
----------------------------
List Of clusters
----------------------------
[Summary(cluster='domain-c8', cluster_name='wcpe2e-compute-cluster', stats=Stats(cpu_used=0, cpu_capacity=0, memory_used=0, memory_capacity=0, storage_used=0, storage_capacity=0), config_status=ConfigStatus(string='RUNNING'), kubernetes_status=KubernetesStatus(string='READY'))]
````
=> new sample for namespace_management list clusters

requirements.txt, setup.py
It looks like you don't really need `suds` or `suds-jurko`. `grep -R suds lib tests` doesn't find anything...
Fixes #286
=> Remove suds(-jurko) dependency

README.md
Remove references of older versions of VC releases
=> Removed references of VC 6.5 and VC 6.7. These releases are officially out of support

README.md
Update local installation of an SDK in README
=> Update local installation of an SDK in README

samples/vsphere/vcenter/crypto_manager/kms/native_key_provider.py
This is a short demo of native key provider APIs in the Autpmation SDK. The demo includes how native key provider can be set as default for the system using pyvmomi.
Below is the output of the demo script: (Excluding initial print of vc url and user name)
```
Create Native Key Provider.
Native Key Provider summary: {provider : native_kms, type : NATIVE, health : ERROR}
Native Key Provider details: {health : ERROR, details : [LocalizableMessage(id='com.vmware.vim.vpxd.encryption.keyProviderNotBackedUp', default_message='Key provider native_kms requires backup.', args=[], params={'keyProviderId': LocalizationParam(s='native_kms', dt=None, i=None, d=None, l=None, format=None, precision=None)}, localized='Key provider native_kms requires backup.')], constraints : {tpm_required : False}, type …
```
=> Demonstrate the Native Key Provider APIs
